const {test,expect}=require('@playwright/test');
test.use({launchOptions:{channel:'msedge'},viewport:{width:1440,height:1000}});
test.setTimeout(120000);
test('atomic XML import and payment reporting',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000/login');await page.locator('#userId').fill('edutax');await page.locator('#password').fill('edutax2026');await expect(page.locator('output')).not.toHaveText('');await page.locator('#captcha').fill((await page.locator('output').innerText()).trim());await page.getByRole('button',{name:'Login',exact:true}).click();await page.waitForURL('**/portal');await page.getByRole('button',{name:/3271022601770007 RAKA/}).click();await page.getByRole('button',{name:/0012345678910000 PT KARYA MANDIRI SEJAHTERA/}).click();
 const db=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('edutax.uny.v1.db')));
 await page.goto('http://localhost:3000/ebupot/bpmp/belum-terbit');
 const row='<Record><Month>10</Month><Year>2024</Year><TIN>3217122601770007</TIN><Name>RAKA</Name><Gross>10000000</Gross><PTKP>K/0</PTKP><TaxObjectCode>21-100-01</TaxObjectCode><NITKU>0012345678910000000000</NITKU></Record>';
 const upload=(s)=>page.getByLabel('Pilih XML bukti potong').setInputFiles({name:'test.xml',mimeType:'application/xml',buffer:Buffer.from(s)});
 await upload(`<EduTaxImport kind="BPMP">${row}<Record/></EduTaxImport>`);await expect(page.getByText(/Record 2:/)).toBeVisible();expect((await db()).bupots.length).toBe(0);
 await upload(`<EduTaxImport kind="BPMP">${row}</EduTaxImport>`);await expect(page.getByText(/1 record berhasil diimpor/)).toBeVisible();await page.getByRole('checkbox',{name:'Pilih RAKA',exact:true}).check();await page.getByRole('button',{name:'Terbitkan',exact:true}).click();await page.locator('#sd-pass').fill('simulasi');await page.getByRole('button',{name:'Konfirmasi Tanda Tangan'}).click();await expect.poll(async()=>(await db()).bupots[0].status).toBe('ISSUED');
 await page.goto('http://localhost:3000/spt');await page.getByRole('button',{name:'+ Buat Konsep SPT',exact:true}).click();await page.getByRole('button',{name:'PPh Pasal 21/26',exact:true}).click();await page.getByRole('button',{name:'Lanjut',exact:true}).click();await page.locator('select').last().selectOption('10');await page.locator('input[type=number]').fill('2024');await page.getByRole('button',{name:'Lanjut',exact:true}).click();await page.getByRole('button',{name:'Buat Konsep SPT',exact:true}).click();await page.waitForURL(/\/spt\/.+/);
 await expect(page.getByRole('button',{name:'Bayar dan Lapor',exact:true})).toBeDisabled();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Bayar dan Lapor',exact:true}).click();await page.locator('#sd-pass').fill('simulasi');await page.getByRole('dialog').getByRole('button',{name:'Simpan',exact:true}).click();await page.getByRole('button',{name:'Konfirmasi Tanda Tangan'}).click();await expect.poll(async()=>(await db()).spts[0].status).toBe('MENUNGGU_PEMBAYARAN');expect((await db()).spts[0].billing.nominal).toBe(200000);
 const billing=page.waitForEvent('download');await page.getByRole('button',{name:'Download Kode Billing'}).click();expect((await billing).suggestedFilename()).toMatch(/^billing-.*\.pdf$/);
 await page.goto('http://localhost:3000/pembayaran');await page.getByRole('link',{name:'Lihat billing dan bayar'}).click();await page.getByRole('button',{name:'Simulasikan Pembayaran'}).click();await page.getByRole('dialog').getByRole('button',{name:'Pembayaran Berhasil'}).click();await expect.poll(async()=>(await db()).spts[0].status).toBe('DILAPORKAN');const id=(await db()).spts[0].id;
 await page.reload();await expect(page.getByRole('button',{name:'Bayar dan Lapor'})).toHaveCount(0);await page.goto('http://localhost:3000/spt');await page.getByRole('button',{name:'SPT Dilaporkan',exact:true}).click();
 for(const name of ['Download Formulir Induk','Download BPE']){const d=page.waitForEvent('download');await page.getByRole('button',{name,exact:true}).click();expect((await d).suggestedFilename()).toMatch(/\.pdf$/);}
 await page.getByRole('button',{name:/0012345678910000 PT KARYA MANDIRI SEJAHTERA/}).click();await page.getByRole('button',{name:/3271022601770007 RAKA/}).click();await page.goto(`http://localhost:3000/spt/${id}`);await expect(page.getByText(/SPT tidak ditemukan/)).toBeVisible();expect(errors).toEqual([]);
});
