/**
 * Konstanta role akses.
 * Nama role disalin apa adanya dari panduan Coretax (slide 45-48), termasuk
 * ejaan "WITHOLDING" yang memang tertulis dengan satu huruf H di dokumen DJP.
 * Jangan "dikoreksi" agar mahasiswa terbiasa dengan penamaan aslinya.
 */

export const ROLES = {
  // Bukti Potong PPh 21/26
  EBUPOT_21_DRAFTER: 'ROLE_CTAS_PORTAL_EBUPOT_21/26_DRAFTER',
  EBUPOT_21_SIGNER: 'ROLE_CTAS_PORTAL_EBUPOT_21/26_SIGNER',

  // Bukti Potong PPh Unifikasi
  EBUPOT_UNIFIKASI_DRAFTER: 'ROLE_CTAS_PORTAL_EBUPOT_DRAFTER',
  EBUPOT_UNIFIKASI_SIGNER: 'ROLE_CTAS_PORTAL_EBUPOT_SIGNER',

  // SPT Masa PPh 21/26
  SPT_21_DRAFTER: 'ROLE_CTAS_PORTAL_ARTICLE_21/26_WITHOLDING_DRAFTER',
  SPT_21_SIGNER: 'ROLE_CTAS_PORTAL_ARTICLE_21/26_WITHOLDING_SIGNER',

  // SPT Masa PPh Unifikasi
  SPT_UNIFIKASI_DRAFTER: 'ROLE_CTAS_PORTAL_TAX_WITHOLDING_DRAFTER',
  SPT_UNIFIKASI_SIGNER: 'ROLE_CTAS_PORTAL_TAX_WITHOLDING_SIGNER',

  // Faktur Pajak & SPT Masa PPN (disiapkan untuk tahap lanjutan)
  TAX_INVOICE_DRAFTER: 'ROLE_CTAS_PORTAL_TAX_INVOICE_DRAFTER',
  TAX_INVOICE_SIGNER: 'ROLE_CTAS_PORTAL_TAX_INVOICE_SIGNER',
  VAT_RETURN_DRAFTER: 'ROLE_CTAS_PORTAL_VAT_TAX_RETURN_DRAFTER',
  VAT_RETURN_SIGNER: 'ROLE_CTAS_PORTAL_VAT_TAX_RETURN_SIGNER',

  // Bea Meterai
  STAMP_DUTY_DRAFTER: 'ROLE_CTAS_PORTAL_STAMP_DUTY_TAX_RETURN_DRAFTER',
  STAMP_DUTY_SIGNER: 'ROLE_CTAS_PORTAL_STAMP_DUTY_TAX_RETURN_SIGNER',

  // SPT Masa selain Unifikasi dan 21/26
  PERIODIC_INCOME_TAX_DRAFTER: 'ROLE_CTAS_PORTAL_PERIODIC_INCOME_TAX_RETURN_DRAFTER',
  PERIODIC_INCOME_TAX_SIGNER: 'ROLE_CTAS_PORTAL_PERIODIC_INCOME_TAX_RETURN_SIGNER',

  // SPT Tahunan
  ANNUAL_TAX_DRAFTER: 'ROLE_CTAS_PORTAL_ANNUAL_TAX_RETURN_DRAFTER',
  ANNUAL_TAX_SIGNER: 'ROLE_CTAS_PORTAL_ANNUAL_TAX_RETURN_SIGNER',

  // Pembayaran
  BALANCE_TRANSFER_SIGNER: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_BALANCE_TRANSFER_SIGNER',
  REFUND_SIGNER: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REFUND_SIGNER',
  INTEREST_COMPENSATION_SIGNER: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_INTEREST_COMPENSATION_SIGNER',
  TAXBORNE_WATERCOMPANY_SIGNER: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_TAXBORNE_BY_GOVERNMENT_WATERCOMPANY_SIGNER',

  // Registrasi & layanan
  REG_BASIC: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REG_BASIC',
  REG_DATA_UPDATE: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REG_DATA_UPDATE',
  REG_DEREGISTRATION_REVOCATION: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REG_DEREGISTRATION_REVOCATION',
  REG_INCOME_WITHHOLDER_COLLECTOR: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REG_INCOME_WITHHOLDER_COLLECTOR',
  REG_REPORTING_FINANCIAL_INSTITUTION: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REG_REPORTING_FINANCIAL_INSTITUTION',
  REG_STAMP_DUTY_COLLECTOR: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REG_STAMP_DUTY_COLLECTOR',
  REG_VAT_APPOINTMENT: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REG_VAT_APPOINTMENT',
  REG_LAND_BUILDING: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REG_LAND_BUILDING_REGISTRATION',
  REG_INACTIVATION_REACTIVATION: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REG_INACTIVATION_REACTIVATION',
  REG_DOMESTIC_ECOMMERCE_VAT: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_REG_DOMESTIC_ECOMMERCE_VAT_COLLECTOR',
  PAY_BASIC: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_PAY_BASIC',
  TPS_BASIC: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_TPS_BASIC',
  TPS_ADDITIONAL: 'ROLE_CTAS_PORTAL_REPRESENTATIVE_EXTERNAL_TPS_ADDITIONAL',
} as const;

export type RoleCode = (typeof ROLES)[keyof typeof ROLES];

/** Label bahasa Indonesia untuk ditampilkan di layar "Tetapkan Role". */
export const ROLE_LABELS: Record<string, string> = {
  [ROLES.EBUPOT_21_DRAFTER]: 'Pembuat draft Bukti Potong PPh Pasal 21/26',
  [ROLES.EBUPOT_21_SIGNER]: 'Penandatangan Bukti Potong PPh Pasal 21/26',
  [ROLES.EBUPOT_UNIFIKASI_DRAFTER]: 'Pembuat draft Bukti Potong PPh Unifikasi',
  [ROLES.EBUPOT_UNIFIKASI_SIGNER]: 'Penandatangan Bukti Potong PPh Unifikasi',
  [ROLES.SPT_21_DRAFTER]: 'Pembuat draft SPT Masa PPh Pasal 21/26',
  [ROLES.SPT_21_SIGNER]: 'Penandatangan SPT Masa PPh Pasal 21/26',
  [ROLES.SPT_UNIFIKASI_DRAFTER]: 'Pembuat draft SPT Masa PPh Unifikasi',
  [ROLES.SPT_UNIFIKASI_SIGNER]: 'Penandatangan SPT Masa PPh Unifikasi',
  [ROLES.TAX_INVOICE_DRAFTER]: 'Pembuat draft faktur pajak',
  [ROLES.TAX_INVOICE_SIGNER]: 'Penandatangan faktur pajak',
  [ROLES.VAT_RETURN_DRAFTER]: 'Pembuat draft SPT Masa PPN',
  [ROLES.VAT_RETURN_SIGNER]: 'Penandatangan SPT Masa PPN',
  [ROLES.STAMP_DUTY_DRAFTER]: 'Pembuat draft SPT Masa Bea Meterai',
  [ROLES.STAMP_DUTY_SIGNER]: 'Penandatangan SPT Masa Bea Meterai',
  [ROLES.PERIODIC_INCOME_TAX_DRAFTER]: 'Pembuat draft SPT Masa selain Unifikasi dan 21/26',
  [ROLES.PERIODIC_INCOME_TAX_SIGNER]: 'Penandatangan SPT Masa selain Unifikasi dan 21/26',
  [ROLES.ANNUAL_TAX_DRAFTER]: 'Pembuat draft SPT Tahunan PPh',
  [ROLES.ANNUAL_TAX_SIGNER]: 'Penandatangan SPT Tahunan PPh',
  [ROLES.BALANCE_TRANSFER_SIGNER]: 'Role untuk Permohonan Pemindahbukuan',
  [ROLES.REFUND_SIGNER]: 'Role untuk Permohonan Pengembalian Pendahuluan',
  [ROLES.INTEREST_COMPENSATION_SIGNER]: 'Role untuk Permohonan Imbalan Bunga',
  [ROLES.TAXBORNE_WATERCOMPANY_SIGNER]: 'Role untuk Permohonan PPh DTP atas Penghasilan PDAM',
  [ROLES.REG_BASIC]: 'Role dasar modul registrasi bagi Kuasa Wajib Pajak',
  [ROLES.REG_DATA_UPDATE]: 'Role untuk Perubahan Data Wajib Pajak',
  [ROLES.REG_DEREGISTRATION_REVOCATION]: 'Role untuk Pencabutan atau Penghapusan NPWP, Objek PBB PSL, Status PKP',
  [ROLES.REG_INCOME_WITHHOLDER_COLLECTOR]: 'Role untuk Penunjukan/Pencabutan Pemotong atau Pemungut PPh/PPN',
  [ROLES.REG_REPORTING_FINANCIAL_INSTITUTION]: 'Role untuk Penetapan/Perubahan Data/Pencabutan Lembaga Keuangan Pelapor/Nonpelapor',
  [ROLES.REG_STAMP_DUTY_COLLECTOR]: 'Role untuk Penetapan/Pencabutan Pemungut Bea Meterai',
  [ROLES.REG_VAT_APPOINTMENT]: 'Role untuk Permohonan Pengukuhan PKP',
  [ROLES.REG_LAND_BUILDING]: 'Role untuk Pendaftaran Objek Pajak PBB PSL',
  [ROLES.REG_INACTIVATION_REACTIVATION]: 'Role untuk Penetapan WP NA atau Pengaktifan Kembali WP NA',
  [ROLES.REG_DOMESTIC_ECOMMERCE_VAT]: 'Role untuk Penunjukan/Pencabutan Pemungut PPN PMSE Dalam Negeri',
  [ROLES.PAY_BASIC]: 'Role dasar modul pembayaran bagi Wakil/Kuasa',
  [ROLES.TPS_BASIC]: 'Role dasar modul Layanan Perpajakan',
  [ROLES.TPS_ADDITIONAL]: 'Role untuk Penyampaian Permohonan Edukasi',
};

/** Pengelompokan role untuk layar pemilihan, mengikuti slide "Jenis Role Akses". */
export const ROLE_GROUPS = [
  { key: 'bp_fp', label: 'Terkait BP/FP', roles: [
    ROLES.EBUPOT_21_DRAFTER, ROLES.EBUPOT_21_SIGNER,
    ROLES.EBUPOT_UNIFIKASI_DRAFTER, ROLES.EBUPOT_UNIFIKASI_SIGNER,
    ROLES.TAX_INVOICE_DRAFTER, ROLES.TAX_INVOICE_SIGNER,
  ]},
  { key: 'spt', label: 'Terkait SPT', roles: [
    ROLES.SPT_21_DRAFTER, ROLES.SPT_21_SIGNER,
    ROLES.SPT_UNIFIKASI_DRAFTER, ROLES.SPT_UNIFIKASI_SIGNER,
    ROLES.VAT_RETURN_DRAFTER, ROLES.VAT_RETURN_SIGNER,
    ROLES.STAMP_DUTY_DRAFTER, ROLES.STAMP_DUTY_SIGNER,
    ROLES.PERIODIC_INCOME_TAX_DRAFTER, ROLES.PERIODIC_INCOME_TAX_SIGNER,
    ROLES.ANNUAL_TAX_DRAFTER, ROLES.ANNUAL_TAX_SIGNER,
  ]},
  { key: 'uang', label: 'Terkait Uang', roles: [ROLES.BALANCE_TRANSFER_SIGNER, ROLES.PAY_BASIC, ROLES.REFUND_SIGNER, ROLES.INTEREST_COMPENSATION_SIGNER, ROLES.TAXBORNE_WATERCOMPANY_SIGNER] },
  { key: 'registrasi', label: 'Terkait Registrasi', roles: [ROLES.REG_BASIC, ROLES.REG_DATA_UPDATE, ROLES.REG_DEREGISTRATION_REVOCATION, ROLES.REG_INCOME_WITHHOLDER_COLLECTOR, ROLES.REG_REPORTING_FINANCIAL_INSTITUTION, ROLES.REG_STAMP_DUTY_COLLECTOR, ROLES.REG_VAT_APPOINTMENT, ROLES.REG_LAND_BUILDING, ROLES.REG_INACTIVATION_REACTIVATION, ROLES.REG_DOMESTIC_ECOMMERCE_VAT] },
  { key: 'layanan', label: 'Terkait Layanan', roles: [ROLES.TPS_BASIC, ROLES.TPS_ADDITIONAL] },
] as const;
